services:
  mysql:
    image: mysql:latest
    container_name: mysql-server_fut
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user_password
      MYSQL_DATABASE: fut_champions
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_fut
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: user_password
    ports:
      - "8080:80"
      
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./projet/html:/var/www/html
    ports:
      - "80:80"
  
volumes:
  mysql-data:
